package com.tourism.booking.audit;

public enum AuditAction {
    USER_REGISTERED,
    BOOKING_CREATED,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_INTENT_CREATED,
    PAYMENT_SUCCESS,
    PAYMENT_FAILURE,
    REFUND_CREATED,
    HOTEL_CREATED,
    HOTEL_UPDATED,
    HOTEL_DELETED,
    ROOM_TYPE_CREATED,
    ROOM_TYPE_UPDATED,
    ROOM_TYPE_DELETED,
    PROMO_CODE_CREATED,
    PROMO_CODE_UPDATED,
    PROMO_CODE_DELETED,
    REVIEW_CREATED,
    REVIEW_DELETED
}
